---
- name: Upgrade Cisco 9200 IOS Switch
  hosts: ftlab01_switch5
  gather_facts: no
  vars:
    tftp_server_ip: "10.15.72.9"
    ansible_command_timeout: 4000  # Set timeout to a higher value

  tasks:
    - name: Backup running configuration to TFTP server
      ansible.netcommon.cli_command:
        command: "copy running-config tftp://{{ tftp_server_ip }}/Ansible-Switch-Backups/{{ inventory_hostname }}-running.cfg"
        prompt:
          - "Address or name of remote host"
          - "Destination filename"
        answer: "\n"

    - name: Upload new IOS image to switch from TFTP server
      ansible.netcommon.cli_command:
        command: "copy tftp://{{ tftp_server_ip }}/cat9k_lite_iosxe.17.12.04.SPA.bin flash:"
        prompt:
          - "Destination filename"
        answer: "\n"