
all:
####################
# Network Switches #
####################
  children:
    all_switches:
      children:
        all_branch_switches:
          children:
            az001: #Phoenix
              hosts:
                az001_switch1:
                  ansible_host: 10.13.214.10
            ftlab: #Sandbox
              hosts:
                ftlab01_switch1:
                  ansible_host: 10.13.130.10
                ftlab01_switch2:
                  ansible_host: 10.13.130.11
            ft002: #Bubolz
              hosts:
                ft002_switch1:
                  ansible_host: 10.13.188.10
                ft002_switch2:
                  ansible_host: 10.13.188.11
                ft002_switchcage1:
                  ansible_host: 10.13.188.14
                ft002_switchsolar1:
                  ansible_host: 10.13.188.12
                ft002_switchsolar2:
                  ansible_host: 10.13.188.13
            ft003: #One Menasha Center
              hosts:
                ft003_core1:
                  ansible_host: 10.13.104.10
                ft003_switch2:
                  ansible_host: 10.13.104.17
                ft003_switch3:
                  ansible_host: 10.13.104.18
                ft003_switch4:
                  ansible_host: 10.13.104.16
                ft003_switch5:
                  ansible_host: 10.13.104.14
                ft003_switch6:
                  ansible_host: 10.13.104.13
                ft003_switch7:
                  ansible_host: 10.13.104.12
                ft003_switch8:
                  ansible_host: 10.13.104.11
                ft003_switch9:
                  ansible_host: 10.13.104.19
            ft004: #Lakeside
              hosts:
                ft004_switch1:
                  ansible_host: 10.13.128.10
                ft004_switch10:
                  ansible_host: 10.13.128.19
                ft004_switch11:
                  ansible_host: 10.13.128.20
                ft004_switch2:
                  ansible_host: 10.13.128.11
                ft004_switch3:
                  ansible_host: 10.13.128.12
                ft004_switch4:
                  ansible_host: 10.13.128.13
                ft004_switch5:
                  ansible_host: 10.13.128.14
                ft004_switch6:
                  ansible_host: 10.13.128.15
                ft004_switch7:
                  ansible_host: 10.13.128.16
                ft004_switch8:
                  ansible_host: 10.13.128.17
                ft004_switch9:
                  ansible_host: 10.13.128.18
            ftdc1: #Fitchburg Data Center
              hosts:
                ftdc1_attdia:
                  ansible_host: 10.13.100.12
                ftdc1_core1:
                  ansible_host: 10.11.100.1
                ftdc1_core2_a:
                  ansible_host: 10.13.100.20
                ftdc1_core2_b:
                  ansible_host: 10.13.100.21
                ftdc1_mgmt1:
                  ansible_host: 10.13.100.11
            ga001: #Atlanta South
              hosts:
                ga001_switch3:
                  ansible_host: 10.13.160.12
            ga002: #Atlanta North
              hosts:
                ga002_switch1:
                  ansible_host: 10.13.196.10
                ga002_switch2:
                  ansible_host: 10.13.196.11
            id001: #Idaho
              hosts:
                id001_switch1:
                  ansible_host: 10.17.149.131
                id001_switch2:
                  ansible_host: 10.17.149.132
            ks001: #Lenexa
              hosts:
                ks001_switch1:
                  ansible_host: 10.13.213.10
                ks001_switch2:
                  ansible_host: 10.13.213.11
            ks002: #Olathe
              hosts:
                ks002_switch1:
                  ansible_host: 10.13.120.10
                ks002_switch10:
                  ansible_host: 10.13.120.19
                ks002_switch11:
                  ansible_host: 10.13.120.20
                ks002_switch2:
                  ansible_host: 10.13.120.11
                ks002_switch3:
                  ansible_host: 10.13.120.12
                ks002_switch4:
                  ansible_host: 10.13.120.13
                ks002_switch5:
                  ansible_host: 10.13.120.14
                ks002_switch6:
                  ansible_host: 10.13.120.15
                ks002_switch7:
                  ansible_host: 10.13.120.16
                ks002_switch8:
                  ansible_host: 10.13.120.17
                ks002_switch9:
                  ansible_host: 10.13.120.18
            ks003: #Smokey Hill Ranch
              hosts:
                ks003_ehouse_switch1:
                  ansible_host: 10.17.142.13
                ks003_switch2:
                  ansible_host: 10.17.142.11
                ranch_switch1:
                  ansible_host: 10.17.142.10
                ranch_switch3:
                  ansible_host: 10.17.142.12
            ok001: #Tulsa
              hosts:
                ok001_switch1:
                  ansible_host: 10.13.124.10
            tn001: #Nashville
              hosts:
                tn001_switch1:
                  ansible_host: 10.13.192.10
                tn001_switch2:
                  ansible_host: 10.13.192.11
                tn001_switch3:
                  ansible_host: 10.13.192.12
            wi001: #Faith University
              hosts:
                wi001_switch1:
                  ansible_host: 10.13.140.10
                wi001_switch2:
                  ansible_host: 10.13.140.11
                wi001_switch3:
                  ansible_host: 10.13.140.12
                wi001_switch4:
                  ansible_host: 10.13.140.13
            wi003: #Neenah (Excellerate)
              hosts:
                wi003_switch1:
                  ansible_host: 10.13.112.10
                wi003_switch2:
                  ansible_host: 10.13.112.11
                wi003_switch3:
                  ansible_host: 10.13.112.12
                wi003_switch4:
                  ansible_host: 10.13.112.13
                wi003_switch5:
                  ansible_host: 10.13.112.14
            wi004: #Green Bay
              hosts:
                wi004_switch1:
                  ansible_host: 10.13.168.10
                wi004_switch2:
                  ansible_host: 10.13.168.11
            wi005: #Appleton (Excellerate)
              hosts:
                wi005_switch1:
                  ansible_host: 10.13.108.10
                wi005_switch2:
                  ansible_host: 10.13.108.11
                wi005_switch3:
                  ansible_host: 10.13.108.12
            wi008: #Madison
              hosts:
                wi008_switch1:
                  ansible_host: 10.13.148.10
                wi008_switch2:
                  ansible_host: 10.13.148.11
            wi011: #Milwaukee
              hosts:
                wi011_switch1:
                  ansible_host: 10.13.144.10
                wi011_switch2:
                  ansible_host: 10.13.144.11
                wi011_switch3:
                  ansible_host: 10.13.144.12
            wi013: #Appleton Tooling
              hosts:
                wi013_switch1:
                  ansible_host: 10.13.208.10
                wi013_switch2:
                  ansible_host: 10.13.208.11
                wi013_switch3:
                  ansible_host: 10.13.208.12
            wi014: #Appleton Flight Center
              hosts:
                wi014_switch1:
                  ansible_host: 10.15.202.10
            wi015: #Middleton Biogas
              hosts:
                wi015_fiber_switch1:
                  ansible_host: 10.13.212.13
                wi015_south_array_switch1:
                  ansible_host: 10.13.212.12
                wi015_switch1:
                  ansible_host: 10.13.212.10
                wi015_switch2:
                  ansible_host: 10.13.212.11
            wi016: #Little Chute
              hosts:
                wi016_switch1:
                  ansible_host: 10.13.134.10
                wi016_switch2:
                  ansible_host: 10.13.134.11
                wi016_switch3:
                  ansible_host: 10.13.134.12
                wi016_switch4:
                  ansible_host: 10.13.134.13
                wi016_switch5:
                  ansible_host: 10.13.134.14
                wi016_switch6:
                  ansible_host: 10.13.134.15
                wi016_switch7:
                  ansible_host: 10.13.134.16
                wi016_switch8:
                  ansible_host: 10.13.134.17
            test1: #Used to confirm ansible will fail
              hosts:
                issiah_testing_testy:
                  ansible_host: 192.168.111.111
            # Add branch switches sites here...
        all_jobsites_switches:
          children:
            knc1a:
              hosts:
                knc1a_switch1:
                  ansible_host: 10.16.6.10
            knc1a_dc2:
              hosts:
                knc1a_dc2_switch1:
                  ansible_host: 10.16.13.10
            leavenworth:
              hosts:
                leavenworth_switch1:
                  ansible_host: 10.16.8.10
            pry8a:
              hosts:
                pry8a_super_switch1:
                  ansible_host: 10.16.4.11
                pry8a_switch1:
                  ansible_host: 10.16.4.10
            pry_wh:
              hosts:
                pry_wh_switch1:
                  ansible_host: 10.16.1.10
            spc:
              hosts:
                spc_switch1:
                  ansible_host: 10.16.170.10
                spc_switch2:
                  ansible_host: 10.16.170.11
                spc_nib_switch2:
                  ansible_host: 10.16.170.18
                spc_inib_switch1:
                  ansible_host: 10.16.170.16
            uno:
              hosts:
                uno_switch1:
                  ansible_host: 10.16.7.10
                uno_switch2:
                  ansible_host: 10.16.7.11
            uno_trailer:
              hosts:
                uno_trailer_switch1:
                  ansible_host: 10.16.12.10
                uno_trailer_switch2:
                  ansible_host: 10.16.12.11
                uno_trailer_switch3:
                  ansible_host: 10.16.12.12
                uno_trailer_switch4:
                  ansible_host: 10.16.12.13
              
            # Add more job sites here...

#####################
# Palo Alto Devices #
#####################
  # children:
  #   all_palo_alto:
      # children:
      #   all_branch_palo_alto:
      #     children:      
      #       az001:
      #         hosts:
      #           az001_pa1:
      #             ansible_host: 10.13.214.1
      #       ftlab_01:
      #         hosts:
      #           ftlab01_pa1:
      #             ansible_host: 10.13.130.1
      #   all_jobsite_palo_alto:
      #     children:      
      #       az001:
      #         hosts:
      #           az001_pa1:
      #             ansible_host: 10.13.214.1
      #       ftlab_01:
      #         hosts:
      #           ftlab01_pa1:
      #             ansible_host: 10.13.130.1

#################
# SDWAN Devices #
################# 
  # children:
  #   all_sdwan:
  #     children:
  #       all_branch_sdwan:
  #         children:      
  #           az001:
  #             hosts:
  #               az001_cgx11:
  #                 ansible_host: 10.13.214.1
  #           ftlab_01:
  #             hosts:
  #               ftlab01_cgx11:
  #                 ansible_host: 10.13.130.1     

#######################################################
# Variables - Will be changed later - Issiah Meddaugh #
#######################################################
  vars:
    ansible_user: default_user
    ansible_password: default_password
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: default_password