---
- name: Upgrade Cisco 9200 IOS Switch
  hosts: ftlab01_switch2
  gather_facts: no
  vars:
    tftp_server_ip: "10.15.72.9"

  tasks:
    - name: Backup running configuration to TFTP server
      ansible.netcommon.cli_command:
        command: "copy running-config tftp://{{ tftp_server_ip }}/Ansible-Switch-Backups/{{ inventory_hostname }}-running.cfg"
        prompt:
          - "Address or name of remote host"
          - "Destination filename"
        answer: "\n"

    - name: Upload new IOS image to switch from TFTP server
      ansible.netcommon.cli_command:
        command: "copy tftp://{{ tftp_server_ip }}/cat9k_lite_iosxe.17.12.04.SPA.bin flash:"
        prompt:
          - "Destination filename"
        answer: "\n"

###############################
######### PAUSED HERE #########
###############################
    - name: Set boot variable to new image
      cisco.ios.ios_config:
        lines:
          - boot system flash:cat9k_lite_iosxe.17.12.04.SPA.bin

    - name: Save configuration
      cisco.ios.ios_command:
        commands:
          - write memory

    - name: Reload switch to apply new image
      cisco.ios.ios_command:
        commands:
          - reload
        confirm: yes

    - name: Verify switch is running new image
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Check new IOS version
      debug:
        msg: "New IOS version: {{ version_output }}"