---
- name: Configure a new port on Cisco switch
  hosts: switches
  gather_facts: no
  collections:
    - cisco.ios
    - ansible.netcommon
  vars:
    port_Gi101_name: GigabitEthernet1/0/11
    port_Gi101_description: "New port configuration"
    port_Gi101_vlan: 10
    port_Gi101_mode: access

    port_Gi102_name: GigabitEthernet1/0/2
    port_Gi102_description: "New port configuration2"
    port_Gi102_vlan: 12
    port_Gi102_mode: access

  tasks:
    - name: Configure interface description
      ios_config:
        lines:
          - description "{{ port_Gi101_description }}"
        parents: "interface {{ port_Gi102_name }}"

    - name: Configure switchport mode
      ios_config:
        lines:
          - switchport mode {{ port_Gi101_mode }}
        parents: "interface {{ port_Gi101_name }}"

    - name: Configure access vlan
      ios_config:
        lines:
          - switchport access vlan {{ port_Gi101_vlan }}
        parents: "interface {{ port_Gi101_name }}"

    - name: Ensure the interface is up
      ios_config:
        lines:
          - no shutdown
        parents: "interface {{ port_Gi101_name }}"

    - name: Configure interface description
      ios_config:
        lines:
          - description "{{ port_Gi102_description }}"
        parents: "interface {{ port_Gi102_name }}"

    - name: Configure switchport mode
      ios_config:
        lines:
          - switchport mode {{ port_Gi102_mode }}
        parents: "interface {{ port_Gi102_name }}"

    - name: Configure access vlan
      ios_config:
        lines:
          - switchport access vlan {{ port_Gi102_vlan }}
        parents: "interface {{ port_Gi102_name }}"

    - name: Ensure the interface is up
      ios_config:
        lines:
          - no shutdown
        parents: "interface {{ port_Gi102_name }}"
