---
- name: Run 'show vlan' on Cisco devices
  hosts: switches
  gather_facts: no
  tasks:
    - name: Execute show vlan command
      ios_command:
        commands: show vlan
      register: vlan_output

    - name: Send VLAN output via email
      mail:
        host: smtp-mail.outlook.com  # Replace with your SMTP server
        port: 587                          # Replace with your SMTP port (usually 587 for TLS)
        username: cmec.scanner@outlook.com # Replace with your email address
        password: GBxpD8pqZYK34hhsA@df    # Replace with your email password
        to: issiah.meddaugh@badgernetworks.org       # Replace with your recipient email address
        subject: "VLAN Output from Switches"
        body: |
          Here is the VLAN configuration output:

          {{ vlan_output.stdout[0] }}

          -- End of Output --
