---
- name: Retrieve VLAN information
  hosts: cisco_switch
  gather_facts: no
  tasks:
    - name: Get VLAN information
      ios_command:
        commands:
          - show vlan brief
      register: vlan_output

    - name: Parse VLAN information
      set_fact:
        vlan_lines: "{{ vlan_output.stdout[0].split('\n') }}"

    - name: Extract VLAN IDs and Names
      set_fact:
        vlan_info: |
          {% for line in vlan_lines %}
            {% if line.startswith(' ') and not line.startswith('----') %}
              {{ line.split()[0] }} {{ line.split()[1] }}
            {% endif %}
          {% endfor %}

    - name: Display VLAN information
      debug:
        msg: "{{ vlan_info }}"
