---
- name: Run 'show vlan' on Cisco devices
  hosts: switches
  gather_facts: no
  tasks:
    - name: Execute show vlan command
      ios_command:
        commands: show vlan brief
      register: vlan_output

    - name: Send VLAN output via email
      mail:
        host: smtp-mail.outlook.com
        port: 587
        username: "cmec.scanner@outlook.com"
        password: "GBxpD8pqZYK34hhsA@df"
        to: "issiah.meddaugh@badgernetworks.org"
        from: "cmec.scanner@outlook.com"
        subject: "VLAN Output from Switches"
        body: |
          Here is the VLAN configuration output:

          {{ vlan_output.stdout[0] }}

          -- End of Output --
