name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug Checkout Directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files in the current working directory:"
          ls -la

      - name: Verify Directory Structure
        run: |
          echo "Listing playbooks directory:"
          ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks || echo "Playbooks directory does not exist"
          echo "Listing inventory directory:"
          ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory || echo "Inventory directory does not exist"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko

      - name: Get the changed playbooks
        id: changed-playbooks
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit found."
            touch changed_files.txt
          fi
          grep "^Ansible/playbooks/.*\.yml" changed_files.txt > playbooks.txt || echo "No playbooks changed" > playbooks.txt

      - name: Display the playbooks that changed
        run: cat playbooks.txt
        
      - name: Run Ansible Playbooks
        if: success()
        run: |
          if [ -s playbooks.txt ]; then
            while IFS= read -r playbook; do
              # Remove leading path segments to get relative path
              relative_playbook=$(echo "$playbook" | sed 's/^Ansible\/playbooks\///')
              echo "Running playbook: /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/$relative_playbook"
              if ! ansible-playbook -i /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory "/home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/$relative_playbook"; then
                echo "Failed to run playbook: $relative_playbook"
                exit 1
              fi
            done < playbooks.txt
          else
            echo "No playbooks to run."
            exit 0
          fi
      
