name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure that we have at least two commits for comparison

      - name: List files in playbooks directory
        run: ls -l /home/meddaugh/ansible/github-infrastructure-repo/Ansible/playbooks

      - name: Verify Directory Structure
        run: |
          echo "Listing playbooks directory:"
          ls -l /home/meddaugh/ansible/github-infrastructure-repo/Ansible/playbooks
          echo "Listing inventory directory:"
          ls -l /home/meddaugh/ansible/github-infrastructure-repo/Ansible/inventory
         

      - name: Get the changed playbooks
        id: changed-playbooks
        run: |
          # Ensure we have a previous commit to compare against
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit found."
            touch changed_files.txt
          fi
          grep "^Ansible/playbooks/.*\.yml" changed_files.txt > playbooks.txt || echo "No playbooks changed" > playbooks.txt

      - name: Display the playbooks that changed
        run: cat playbooks.txt

      - name: Run Ansible Playbooks
        if: success()
        run: |
          if [ -s playbooks.txt ]; then
            while IFS= read -r playbook; do
              # Remove leading path segments to get relative path
              relative_playbook=$(echo "$playbook" | sed 's/^Ansible\/playbooks\///')
              ansible-playbook -i /home/meddaugh/ansible/github-infrastructure-repo/Ansible/inventory "/home/meddaugh/ansible/github-infrastructure-repo/Ansible/playbooks/$relative_playbook"
            done < playbooks.txt
          else
            echo "No playbooks to run."
          fi
