name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Path to the playbook to run'
        required: true
        default: '/home/meddaugh/ansible/github-infrastructure-repo/Ansible/playbooks/example-playbook.yml'

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.10.12'

      - name: Check Python Version
        run: python3 --version
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: | 
          ansible-playbook -i /home/meddaugh/ansible/github-infrastructure-repo/Ansible/inventory ${{ github.event.inputs.playbook }}
