name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to install Python and Pipx
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Ensure pipx is installed
      - name: Install pipx
        run: python -m pip install --user pipx

      # Install Ansible Core with force to ensure clean installation
      - name: Force Reinstall Ansible Core
        run: pipx install ansible-core --force

      # Install ansible-pylibssh to prevent fallback to Paramiko
      - name: Install ansible-pylibssh
        run: pipx inject ansible-core ansible-pylibssh

      # Add a step to install Paramiko as a backup in case it's still needed
      - name: Install Paramiko
        run: pipx inject ansible-core paramiko

      # Activate the virtual environment to ensure correct paths
      - name: Activate Virtual Environment
        run: source /opt/pipx/venvs/ansible-core/bin/activate

      # Print Python Path and Installed Packages for debugging
      - name: Print Python Path and Installed Packages
        run: |
          which python
          python -m pip list

      # Run the Ansible playbook
      - name: Run Ansible Playbook
        run: ansible-playbook /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/configure_int-ports.yml
        env:
          ANSIBLE_CONFIG: /home/runner/work/Infrastructure-/Infrastructure-/ansible.cfg

      # Ensure that the playbook runs correctly and handles failures
      - name: Ensure Playbook Success
        if: failure()
        run: exit 1
