name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Path to the playbook to run'
        required: true
        default: 'ansible/playbooks/example-playbook.yml'

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Align with your local environment

      - name: Install dependencies
        run: |
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory ${{ github.event.inputs.playbook }}
