name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Install Ansible Core
        run: pipx install ansible-core

      - name: Install ansible-pylibssh
        run: pipx inject ansible-core ansible-pylibssh

      - name: Install Paramiko
        run: pipx inject ansible-core paramiko

      - name: List files in playbooks directory
        run: ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks

      - name: Verify Directory Structure
        run: |
          echo "Listing playbooks directory:"
          ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks
          echo "Listing inventory directory:"
          ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory

      - name: Get the changed playbooks
        id: changed-playbooks
        run: |
          # Ensure we have a previous commit to compare against
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit found."
            touch changed_files.txt
          fi
          grep "^Ansible/playbooks/.*\.yml" changed_files.txt > playbooks.txt || echo "No playbooks changed" > playbooks.txt

      - name: Display the playbooks that changed
        run: cat playbooks.txt

      - name: Run Ansible Playbooks
        if: success()
        run: |
          if [ -s playbooks.txt ]; then
            while IFS= read -r playbook; do
              # Remove leading path segments to get relative path
              relative_playbook=$(echo "$playbook" | sed 's/^Ansible\/playbooks\///')
              echo "Running playbook: /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/$relative_playbook"
              ansible-playbook -i /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory "/home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/$relative_playbook" -vvv || { echo "Failed to run playbook: $relative_playbook"; exit 1; }
            done < playbooks.txt
          else
            echo "No playbooks to run."
            exit 0
          fi

