name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible paramiko

      - name: Verify Directory Structure
        run: |
          echo "Listing playbooks directory:"
          ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks
          echo "Listing inventory directory:"
          ls -l /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory

      - name: Get the changed playbooks
        id: changed-playbooks
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit found."
            touch changed_files.txt
          fi
          grep "^Ansible/playbooks/.*\.yml" changed_files.txt > playbooks.txt || echo "No playbooks changed" > playbooks.txt

      - name: Display the playbooks that changed
        run: cat playbooks.txt

      - name: Create Ansible configuration
        run: |
          echo "[defaults]" > ansible.cfg
          echo "inventory = /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory" >> ansible.cfg
          echo "[ssh_connection]" >> ansible.cfg
          echo "ssh_args = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" >> ansible.cfg
          echo "[defaults]" >> ansible.cfg
          echo "remote_user = admin" >> ansible.cfg
          echo "ansible_ssh_pass = admin" >> ansible.cfg

      - name: Check for playbooks and run them
        run: |
          if [ -s playbooks.txt ]; then
            while IFS= read -r playbook; do
              relative_playbook=$(echo "$playbook" | sed 's/^Ansible\/playbooks\///')
              echo "Running playbook: /home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/$relative_playbook"
              ansible-playbook -i /home/runner/work/Infrastructure-/Infrastructure-/Ansible/inventory "/home/runner/work/Infrastructure-/Infrastructure-/Ansible/playbooks/$relative_playbook" || { echo "Failed to run playbook: $relative_playbook"; exit 1; }
            done < playbooks.txt
          else
            echo "No playbooks to run."
            exit 0
          fi
