name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Install Ansible Core
        run: pipx install ansible-core

      - name: Install ansible-pylibssh
        run: pipx inject ansible-core ansible-pylibssh

      - name: Install Paramiko
        run: pipx inject ansible-core paramiko

      - name: Run Ansible Playbook
        run: ansible-playbook Ansible/playbooks/configure_int-ports.yml
        env:
          ANSIBLE_CONFIG: Ansible/ansible.cfg

      - name: Verify playbook success
        if: failure()
        run: exit 1
